# Generated by Django 2.2.10 on 2020-05-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='port',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
