# Generated by Django 3.0.6 on 2020-05-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('sender', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'default_related_name': 'blocks',
            },
        ),
    ]
