# Generated by Django 2.2.10 on 2020-05-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_configurations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionFeeTier',
            new_name='SelfTransactionFeeTier',
        ),
        migrations.AlterModelOptions(
            name='selftransactionfeetier',
            options={'default_related_name': 'self_transaction_fee_tiers'},
        ),
    ]
