# Generated by Django 2.2.10 on 2020-05-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_configurations', '0002_selfconfiguration_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfconfiguration',
            name='port',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
