ACCEPTED = 'ACCEPTED'
DECLINED = 'DECLINED'
PENDING = 'PENDING'

REGISTRATION_STATUS_CHOICES = [
    (ACCEPTED, ACCEPTED),
    (DECLINED, DECLINED),
    (PENDING, PENDING),
]

BANK = 'BANK'

NODE_TYPE_CHOICES = [
    (BANK, BANK),
]
