# Generated by Django 3.0.6 on 2020-06-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validator',
            old_name='seed_hash',
            new_name='seed_block_hash',
        ),
    ]
