# Generated by Django 3.0.6 on 2020-06-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validator',
            name='seed_block_hash',
        ),
        migrations.AddField(
            model_name='validator',
            name='seed_block_identifier',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
