# Generated by Django 3.0.6 on 2020-06-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0002_auto_20200612_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validator',
            name='head_hash',
        ),
    ]
