# Generated by Django 2.2.10 on 2020-05-13 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0002_auto_20200513_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='trust',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
