# Generated by Django 2.2.10 on 2020-05-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0004_auto_20200513_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
