# Generated by Django 2.2.10 on 2020-05-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0005_validator_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
