# Generated by Django 2.2.10 on 2020-05-16 17:54

import django.core.validators
from django.db import migrations, models
import v1.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', models.DecimalField(decimal_places=16, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0), v1.utils.validators.validate_is_real_number])),
                ('balance_key', models.CharField(max_length=256)),
                ('recipient', models.CharField(max_length=256)),
                ('sender', models.CharField(max_length=256)),
                ('signature', models.CharField(max_length=256)),
                ('validated', models.BooleanField(default=False)),
            ],
            options={
                'default_related_name': 'transactions',
            },
        ),
    ]
