# Generated by Django 2.2.10 on 2020-05-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='signature',
            field=models.CharField(default='3432423gfs', max_length=256),
            preserve_default=False,
        ),
    ]
