# Generated by Django 2.2.10 on 2020-05-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_configurations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodeconfiguration',
            old_name='default_tx_fee',
            new_name='default_transaction_fee',
        ),
    ]
