# Generated by Django 2.2.10 on 2020-05-15 23:39

import django.core.validators
from django.db import migrations, models
import v1.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('node_configurations', '0002_auto_20200515_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFeeTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=16, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0), v1.utils.validators.validate_is_real_number])),
                ('trust', models.DecimalField(decimal_places=2, default=0, max_digits=5, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'default_related_name': 'node_configurations',
            },
        ),
    ]
