# Generated by Django 2.2.10 on 2020-05-16 19:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import v1.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0002_validatortransactionfeetier'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('fee', models.DecimalField(decimal_places=16, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0), v1.utils.validators.validate_is_real_number])),
                ('status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED'), ('PENDING', 'PENDING')], default='PENDING', max_length=8)),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_registrations', to='validators.Validator')),
            ],
            options={
                'default_related_name': 'bank_registrations',
            },
        ),
        migrations.DeleteModel(
            name='ValidatorRegistration',
        ),
    ]
