# Generated by Django 3.0.6 on 2020-07-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
        ('invalid_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidblock',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invalid_blocks', to='blocks.Block'),
        ),
    ]
