# Generated by Django 3.0.6 on 2020-06-25 00:26

from django.db import migrations, models
import thenewboston.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bank_registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankregistration',
            name='registration_block_signature',
            field=models.CharField(max_length=128, unique=True, validators=[thenewboston.utils.validators.validate_is_signature_length]),
        ),
    ]
