# Generated by Django 3.1.6 on 2021-02-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='fee',
            field=models.CharField(blank=True, choices=[('BANK', 'BANK'), ('PRIMARY_VALIDATOR', 'PRIMARY_VALIDATOR')], max_length=17),
        ),
    ]
