# Generated by Django 3.1.8 on 2021-04-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0002_banktransaction_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='memo',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
