name: Test

on: [pull_request]


jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    name: Testing Python ${{ matrix.python-version }}

    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_DB: thenewboston
          POSTGRES_USER: thenewboston
          POSTGRES_PASSWORD: thenewboston
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install self
        run: pip install -r requirements/production.txt

#      - name: Lint with flake8
#        run: flake8 .

      - name: Test with pytest
        run: pytest -n auto
        env:
          DJANGO_APPLICATION_ENVIRONMENT: test
          REDIS_HOST: redis
          POSTGRES_HOST: postgres
          POSTGRES_DB: thenewboston
          POSTGRES_USER: thenewboston
          POSTGRES_PASSWORD: thenewboston
          SECRET_KEY: somesecret
